- hosts: es_node1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "1g"
    es_api_basic_auth_username: geic
    es_api_basic_auth_password: Asiainfo@2018
    es_config:
      cluster.name: "geic-cluster"
      discovery.zen.ping.unicast.hosts: ["10.12.3.5:9300", "10.12.3.7:9300", "10.12.3.10:9300"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugin_ik: true

- hosts: es_node2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "node2"
    es_heap_size: "1g"
    es_api_basic_auth_username: geic
    es_api_basic_auth_password: Asiainfo@2018
    es_config:
      cluster.name: "geic-cluster"
      discovery.zen.ping.unicast.hosts: ["10.12.3.5:9300", "10.12.3.7:9300", "10.12.3.10:9300"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugin_ik: true

- hosts: es_node3
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "node3"
    es_heap_size: "1g"
    es_api_basic_auth_username: geic
    es_api_basic_auth_password: Asiainfo@2018
    es_config:
      cluster.name: "geic-cluster"
      discovery.zen.ping.unicast.hosts: ["10.12.3.5:9300", "10.12.3.7:9300", "10.12.3.10:9300"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugin_ik: true    
