---

- hosts: ftp
  roles:
    - franklinkim.vsftpd
  vars:
    vsftpd_users:
       - username: geic
         name: FTP User GEIC
         # python -c 'import crypt; print crypt.crypt("ftpuser", "Asiainfo@2018")'
         password: 'AsZC/619xfPL6'
    vsftpd_config:
      log_ftp_protocol: YES
      local_enable: YES
      write_enable: YES
      xferlog_enable: YES
      listen_port: 21
