---
- name: install mysql
  hosts: mysql
  vars:
    - mysql_root_password: 4KRckdKc8d5YMiMh
      mysql_port: "3306"
      mysql_bind_address: '0.0.0.0'
      mysql_datadir: /data/mysql/data
      mysql_database:
      - name: geic_manage
        encoding: utf8
        collation: utf8_general_ci
      mysql_users:
      - name: geic
        host: "%"
        password: Asiainfo@2018
        priv: "geic_manage.*:ALL"
      mysql_max_binlog_size: "100M"
      mysql_binlog_format: "ROW"
      mysql_expire_logs_days: "10"
      mysql_replication_role: ''
      mysql_replication_master: ''
      mysql_replication_user: []
  roles:
  - role: geerlingguy.mysql 
    become: yes
