---
- name: install mysql
  hosts: mysql
  vars:
    - mysql_root_password: Asiainfo@2018
      mysql_port: "3306"
      mysql_bind_address: '0.0.0.0'
      mysql_datadir: /data/mysql/data
      mysql_database:
      - name: geic_manage
        encoding: utf8
        collation: utf8_general_ci
      mysql_users:
      - name: geic
        host: "%"
        password: Asiainfo@2018
        priv: "geic_manage.*:ALL"
      mysql_max_binlog_size: "100M"
      mysql_binlog_format: "ROW"
      mysql_expire_logs_days: "10"
      mysql_replication_role: ''
      mysql_replication_master: ''
      mysql_replication_user: []
  roles:
  - role: geerlingguy.mysql 
    become: yes


- name: Install oneproxy (double master)
  hosts: mysql
  gather_facts: false
  vars:
    mysql_user: geic
    mysql_password: Asiainfo@2018
    mysql_root_password: Asiainfo@2018
    mysql_secret_password: D58788CC6CD75A2A9A05955A4C95CF92459C18E1
    master_01: 10.12.3.2
    master_02: 10.12.3.9
  roles:
  - role: oneproxy
    become: yes