---
- name: Download ik plugin
  get_url:
    url:  https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.4.0/elasticsearch-analysis-ik-6.4.0.zip
    dest: /opt/elasticsearch-analysis-ik-6.4.0.zip

- name: unarchieve zip file
  unarchive: src=/opt/elasticsearch-analysis-ik-6.4.0.zip dest=/usr/share/elasticsearch/plugins/ik creates=/usr/share/elasticsearch/plugins/ik copy=no
