---

- name: Managing users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.username | default(item.username) }}"
    password: "{{ item.password }}"
    shell: /usr/sbin/nologin
  with_items: "{{ vsftpd_users }}"
